source 'https://rubygems.org'
ruby '1.9.3'

gem 'dashing'
gem 'github_api'
gem 'activesupport'
gem 'xml-simple'
gem 'harvested'
gem 'execjs'
gem 'therubyracer'
gem 'rest-graph'
gem 'rest-client'
gem 'json'
